name: Publish updated tools

on:
  pull_request:
    types:
      - closed

jobs:
  publish-updated-tools:
    name: Publish updated tools
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'update/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pesde
        uses: axiom-co/setup-pesde@b690699ace34169731b6b2a1c93b2008472038a7
        with:
          cache: true
      - name: Publish
        run: |
          branch="${{ github.head_ref }}"
          package="${branch#update/}"

          echo "Publishing '$package'..."
          cd "bins/$package"

          # Fetch & loop through commits
          response=$(curl "${{ github.event.pull_request.commits_url }}")
          commits="$(echo "$response" | jq -r '.[].sha')"
          while read -r commit; do
            # Fetch & checkout the commit
            git fetch origin "$commit"
            git checkout "$commit"
            
            # Publish
            pesde publish -y
          done <<< "$commits"
